basePath: /api
consumes:
- application/json
host: 127.0.0.1:3000
info:
  contact: {}
  description: GoBet - A sports Bet platform.
  title: GoBet
  version: 1.0.0
paths: {}
produces:
- application/json
swagger: "2.0"
